name: Device tree validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - qcom-sdm660-6.*.y
    tags:
      - v*-sdm660
jobs:
  check-dbts:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          sudo apt install -yqq bison build-essential device-tree-compiler flex gcc-aarch64-linux-gnu python3 python3-dev python3-venv swig
      - name: Prepare build direcotory
        run: |
          mkdir build-dtbs-check
      - name: Prepare config
        run: |
          make O=build-dtbs-check ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig sdm660_defconfig
      - name: Compile DTBs
        run: |
          make O=build-dtbs-check ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dtbs
      - name: Check DTBs
        run: |
          python3 -m venv venv_dtschema
          . venv_dtschema/bin/activate
          pip3 install dtschema
          make O=build-dtbs-check ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CHECK_DTBS=y qcom/sdm630-*.dtb qcom/sdm636-*.dtb qcom/sdm660-*.dtb
          deactivate
          rm -r venv_dtschema
